nrwl/angular-rspack

packages/angular-rspack/package.json, packages/angular-rspack/src/lib/config/create-config.ts, packages/angular-rspack/src/lib/config/create-config.unit.test.ts, packages/angular-rspack/tsconfig.spec.json
There is currently no way to configure different configurations that replicate the `angular.json` configurations behaviour.
Add `withConfigurations` to replicate the behaviour
=> feat(angular-rspack): add withConfigurations

e2e/fixtures/rspack-csr-css/rspack.config.js, packages/angular-rsbuild/src/lib/config/create-config.integration.test.ts, packages/angular-rsbuild/src/lib/config/create-config.ts, packages/angular-rsbuild/src/lib/models/normalize-options.ts, packages/angular-rsbuild/src/lib/models/plugin-options.ts, packages/angular-rspack-compiler/src/compilation/setup-compilation.integration.test.ts, packages/angular-rspack-compiler/src/compilation/setup-compilation.ts, packages/angular-rspack-compiler/src/compilation/setup-compilation.unit.test.ts, packages/angular-rspack-compiler/src/compilation/setup-with-paralell-compilation.ts, packages/angular-rspack-compiler/src/compilation/setup-with-paralell-compilation.unit.test.ts, packages/angular-rspack/src/lib/config/create-config.ts, packages/angular-rspack/src/lib/config/create-config.unit.test.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/plugins/angular-rspack-plugin.ts
`tsconfigPath` is currently used to handle specifying a tsconfig file.
`tsConfig` should be used to handle specifying a tsconfig file to match Angular's schema
=> feat(angular-rspack,angular-rsbuild): rename tsconfigPath to tsConfig

apps/docs/rsbuild.config.ts, packages/angular-rsbuild/src/lib/config/create-config.integration.test.ts, packages/angular-rsbuild/src/lib/config/create-config.ts, packages/angular-rsbuild/src/lib/models/normalize-options.ts, packages/angular-rsbuild/src/lib/models/plugin-options.ts, packages/angular-rspack-compiler/src/compilation/augments.ts, packages/angular-rspack-compiler/src/compilation/setup-compilation.integration.test.ts, packages/angular-rspack-compiler/src/compilation/setup-compilation.ts, packages/angular-rspack-compiler/src/compilation/setup-compilation.unit.test.ts, packages/angular-rspack-compiler/src/compilation/setup-with-paralell-compilation.unit.test.ts, packages/angular-rspack-compiler/src/models/index.ts, packages/angular-rspack-compiler/src/models/inline-style-extension.ts, packages/angular-rspack-compiler/src/models/inline-style-language.ts, packages/angular-rspack/src/lib/config/create-config.unit.test.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/plugins/angular-rspack-plugin.ts
The property `inlineStylesExtension` is currently used to determine what style processor to use
Rename the property to `inlineStyleLanguage` to match the angular schema
=> feat(angular-rspack,angular-rsbuild): rename inlineStylesExtension to inlineStyleLanguage

packages/angular-rsbuild/src/lib/config/create-config.ts, packages/angular-rsbuild/src/lib/models/normalize-options.ts, packages/angular-rsbuild/src/lib/models/plugin-options.ts, packages/angular-rspack/src/lib/config/create-config.ts, packages/angular-rspack/src/lib/config/create-config.unit.test.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts
There is currently no method other than setting `NODE_ENV` to turn optimizations off.
Add an `optimization` property to allow configuring optimizations.
=> feat(angular-rspack,angular-rsbuild): add optimization option

apps/docs/rsbuild.config.ts, e2e/fixtures/rsbuild-ssr-css/rsbuild.config.ts, e2e/fixtures/rspack-ssr-css/rspack.config.js, packages/angular-rsbuild/src/lib/config/create-config.ts, packages/angular-rsbuild/src/lib/config/create-config.unit.test.ts, packages/angular-rsbuild/src/lib/models/normalize-options.ts, packages/angular-rsbuild/src/lib/models/normalize-options.unit.test.ts, packages/angular-rsbuild/src/lib/models/plugin-options.ts, packages/angular-rspack/src/lib/config/create-config.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/plugins/ng-rspack.ts
SSR Entry point is currently provided via `ssrEntry` property.
Angular CLI uses a boolean and object union type for `ssr`. Refactor to use that instead to align.
=> feat(angular-rspack,angular-rsbuild): rename ssrEntry to ssr.entry

e2e/fixtures/rspack-csr-css/rspack.config.js, packages/angular-rsbuild/src/lib/config/__snapshots__/create-config.csr.ts, packages/angular-rsbuild/src/lib/config/__snapshots__/create-config.ssr.ts, packages/angular-rsbuild/src/lib/config/create-config.ts, packages/angular-rsbuild/src/lib/config/helpers.ts, packages/angular-rsbuild/src/lib/models/normalize-options.ts, packages/angular-rsbuild/src/lib/models/plugin-options.ts, packages/angular-rspack/src/lib/config/create-config.ts, packages/angular-rspack/src/lib/config/create-config.unit.test.ts, packages/angular-rspack/src/lib/config/helpers.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts
There is no option to control hashing of outputs created by rspack
Add `outputHashing` option aligned with Angular CLI to provide option to configure hashing
=> feat(angular-rspack,angular-rsbuild): add outputHashing option

packages/angular-rsbuild/src/lib/config/create-config.unit.test.ts, packages/angular-rsbuild/src/lib/models/normalize-options.ts, packages/angular-rsbuild/src/lib/models/normalize-options.unit.test.ts, packages/angular-rsbuild/src/lib/models/plugin-options.ts, packages/angular-rsbuild/src/lib/plugin/plugin-angular.ts, packages/angular-rsbuild/src/lib/plugin/plugin-hoisted-js-transformer.ts, packages/angular-rspack/src/lib/config/create-config.unit.test.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/plugins/angular-rspack-plugin.ts, packages/angular-rspack/src/lib/plugins/ng-rspack.ts
The advanced optimizations performed by the JS transformer are not disabled when `aot: false` or `optimizations: false`
The advanced optimizations performed by the JS transformer should be disabled when `aot: false` or `optimizations: false`.
Note: they should be disabled when `aot === false && optimizations.scripts === false`, but the fine-grained optimizations are not yet supported.
=> feat(angular-rspack,angular-rsbuild): turn on/off advanced optimizations based on provided options

e2e/fixtures/rspack-csr-css/rspack.config.js, packages/angular-rsbuild/src/lib/config/create-config.integration.test.ts, packages/angular-rsbuild/src/lib/config/create-config.ts, packages/angular-rsbuild/src/lib/config/create-config.unit.test.ts, packages/angular-rsbuild/src/lib/models/normalize-options.ts, packages/angular-rsbuild/src/lib/models/normalize-options.unit.test.ts, packages/angular-rsbuild/src/lib/models/plugin-options.ts, packages/angular-rsbuild/src/lib/plugin/plugin-hoisted-js-transformer.ts, packages/angular-rspack/src/lib/config/create-config.ts, packages/angular-rspack/src/lib/config/create-config.unit.test.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/plugins/angular-rspack-plugin.ts, packages/angular-rspack/src/lib/plugins/ng-rspack.ts
The `root` option is not required and can be inferred
Remove the `root` option and infer it based on cwd of process
=> feat(angular-rspack,angular-rsbuild): remove root from api

e2e/fixtures/rspack-csr-css/rspack.config.js, packages/angular-rspack/package.json, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/plugins/ng-rspack.ts, pnpm-lock.yaml
Add support for the `extractLicenses` option.
=> feat(angular-rspack): support `extractLicenses` option

package.json, packages/angular-rspack/eslint.next.config.js, packages/angular-rspack/package.json, packages/angular-rspack/src/lib/config/style-config-utils.ts, packages/angular-rspack/src/lib/config/style-config-utils.unit.test.ts, pnpm-lock.yaml
- fix(angular-rspack): sass-loader should not be required when using css
- fix(angular-rspack): sass-loader should not be required when using css
=> fix(angular-rspack): sass-loader should not be required when using css

e2e/fixtures/rspack-csr-css/rspack.config.js, eslint.config.js, packages/angular-rsbuild/src/lib/config/create-config.ts, packages/angular-rsbuild/src/lib/models/normalize-options.ts, packages/angular-rsbuild/src/lib/models/normalize-options.unit.test.ts, packages/angular-rsbuild/src/lib/models/plugin-options.ts, packages/angular-rsbuild/src/lib/plugin/plugin-hoisted-js-transformer.ts, packages/angular-rspack/src/lib/config/create-config.ts, packages/angular-rspack/src/lib/config/create-config.unit.test.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/plugins/angular-rspack-plugin.ts, packages/angular-rspack/src/lib/plugins/ng-rspack.ts
Add `root` option and normalize `tsConfig` to avoid having to provide an absolute path.
=> feat(angular-rspack,angular-rsbuild): add `root` option and improve `tsConfig` handling

packages/angular-rspack/src/lib/config/create-config.unit.test.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/models/unsupported-options.ts
Update `createConfig` public API:
- set all options as optional and normalize them accordingly
- add all currently unsupported options and warn when used
=> feat(angular-rspack): improve createConfig public api

packages/angular-rspack/src/lib/models/augmented-compilation.ts, packages/angular-rspack/src/lib/plugins/loaders/angular-transform.loader.ts, packages/angular-rspack/src/lib/plugins/loaders/angular-transform.loader.unit.test.ts
This PR includes: 
- nonbreaking adoptions of the loader function to be able to test the cache
- refinement of types
- unit tests for `angular-transform.loader.ts`
=> test(angular-rspack): add unit tests for angular loader

packages/angular-rspack/src/lib/config/create-config.ts, packages/angular-rspack/src/lib/config/create-config.unit.test.ts, packages/angular-rspack/src/lib/config/dev-server-config-utils.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/models/unsupported-options.ts
In `@nx/angular-rspack` the `allowedHosts` option is always set to `auto`. User provided options are ignored.
Use `allowedHosts` option to determine the array of hosts the dev server can accept connections from. Aternatively, if set to true, `'all'` is used.
=> feat(angular-rspack): add allowedHosts option

packages/angular-rsbuild/src/lib/config/create-config.ts, packages/angular-rsbuild/src/lib/models/plugin-options.ts, packages/angular-rspack/src/lib/config/create-config.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/unsupported-options.ts
The `preserveSymlinks` option is currently a no-op and therefore real files are resolved.
Support `preserveSymlinks` option and allow the symlinked files to be used
=> feat(angular-rspack,angular-rsbuild): add preserveSymlinks option

packages/angular-rsbuild/src/lib/config/create-config.ts, packages/angular-rsbuild/src/lib/config/helpers.ts, packages/angular-rsbuild/src/lib/models/normalize-options.ts, packages/angular-rsbuild/src/lib/models/plugin-options.ts, packages/angular-rspack/src/lib/config/create-config.ts, packages/angular-rspack/src/lib/config/helpers.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/models/unsupported-options.ts
Output paths are always cleaned by default before the next build.
Add `deleteOutputPath` option to configure if output paths are cleaned before build
=> feat(angular-rspack,angular-rsbuild): add deleteOutputPath option

packages/angular-rsbuild/src/lib/config/create-config.ts, packages/angular-rsbuild/src/lib/models/normalize-options.ts, packages/angular-rsbuild/src/lib/models/plugin-options.ts, packages/angular-rspack/src/lib/config/create-config.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/models/unsupported-options.ts
The `externalDependencies` option is currently not supported and does nothing. This means to define externals for runtime, the user needed to customise the `rspack` and `rsbuild` configs manually.
Support the `externalDependencies` option
=> feat(angular-rspack,angular-rsbuild): add externalDependencies option

package.json, packages/angular-rspack/package.json, packages/angular-rspack/src/lib/config/create-config.ts, packages/angular-rspack/src/lib/config/create-config.unit.test.ts, pnpm-lock.yaml
The `NGRS_CONFIG` env var for passing in specific configurations does not support passing multiple configurations.
The `NGRS_CONFIG` env var should support comma-seperated configurations and `createConfig` should handle it correctly
=> fix(angular-rspack): multiple configurations

packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/models/unsupported-options.ts, packages/angular-rspack/src/lib/plugins/angular-rspack-plugin.ts, packages/angular-rspack/src/lib/utils/get-locale-base-href.ts, packages/angular-rspack/src/lib/utils/url-join.ts
Service Worker is not supported in Angular Rspack.
The `serviceWorker` property is ignored
Service Workers should be supported
=> feat(angular-rspack): add service-worker support

packages/angular-rspack/src/lib/plugins/ng-rspack.ts
When we define `ngDevMode` via `DefinePlugin` we're currently setting it to `{}` in dev.
It should not be set at all in `DefinePlugin` when in devMode
=> fix(angular-rspack): ensure ngDevMode set correctly by DefinePlugin

packages/angular-rspack/package.json, pnpm-lock.yaml
`@nx/angular-rspack` expects `@angular/localize` to always be present as a defined peer dependency.
This is only the case for i18n projects.
Mark `@angular/localize` as an optional peer dependency
=> fix(angular-rspack): mark @angular/localize as optional peer dep

packages/angular-rspack/src/lib/models/normalize-options.ts
`createConfig` currently relies on the ability to create an Nx Graph
`createConfig` does not rely on Nx Graph
=> fix(angular-rspack): do not rely on nx workspace

packages/angular-rspack/src/lib/plugins/loaders/angular-transform.loader.ts
Angular Rspack does not compile correctly on Windows.
It searches the TS File Cache for the transformed app source with an invalid path - the disk drive is stripped from the TS File Cache on entry but not on retrieval.
Strip the disk drive path from the `resourcePath` in the loader to ensure transformed contents are found correctly.
Fixes #53
=> fix(angular-rspack): handle windows disk drive in loader #53

e2e/fixtures/rspack-csr-css/package.json, packages/angular-rspack/src/lib/config/config-utils/browser-config.ts, packages/angular-rspack/src/lib/config/config-utils/common-config.ts, packages/angular-rspack/src/lib/config/config-utils/dev-server-config-utils.ts, packages/angular-rspack/src/lib/config/config-utils/entry-points.ts, packages/angular-rspack/src/lib/config/config-utils/helpers.ts, packages/angular-rspack/src/lib/config/config-utils/optimization-config.ts, packages/angular-rspack/src/lib/config/config-utils/server-config.ts, packages/angular-rspack/src/lib/config/config-utils/sourcemap-utils.ts, packages/angular-rspack/src/lib/config/config-utils/style-config-utils.ts, packages/angular-rspack/src/lib/config/config-utils/user-defined-config-helpers.ts, packages/angular-rspack/src/lib/config/create-config.ts, packages/angular-rspack/src/lib/config/create-config.unit.test.ts, packages/angular-rspack/src/lib/index.ts, packages/angular-rspack/src/lib/plugins/ng-rspack.ts
The `createConfig` function will default to `production` when `NGRS_CONFIG` is not provided.
This includes for launching the dev server.
When running `rspack serve` the `createConfig` should default to `development`.
=> feat(angular-rspack): use development config for serve

packages/angular-rspack/src/lib/config/config-utils/browser-config.ts, packages/angular-rspack/src/lib/config/config-utils/common-config.ts, packages/angular-rspack/src/lib/config/config-utils/dev-server-config-utils.ts, packages/angular-rspack/src/lib/config/config-utils/server-config.ts, packages/angular-rspack/src/lib/config/create-config.ts, packages/angular-rspack/src/lib/config/create-config.unit.test.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/models/unsupported-options.ts
Add support for the following dev-server options:
- `headers`
- `liveReload`
- `publicHost`
- `servePath`
=> feat(angular-rspack): add support for more devServer options

packages/angular-rspack/package.json, pnpm-lock.yaml
Update the minimum supported version of `@rspack/core` package to **1.3.5**. This is required to be able to use resolver restrictions as Regex, which was only added in that version (https://github.com/web-infra-dev/rspack/commit/ebef5d0aff42026cbe2635721365e5cc87eed888).
=> fix(angular-rspack): update the minimum supported version of `@rspack/core`

e2e/fixtures/rspack-csr-css/src/app/app.component.css, e2e/fixtures/rspack-csr-css/src/app/app.component.html, e2e/fixtures/rspack-csr-scss/src/app/app.component.html, e2e/fixtures/rspack-csr-scss/src/app/app.component.scss, packages/angular-rsbuild/src/lib/plugin/plugin-hoisted-js-transformer.ts, packages/angular-rspack-compiler/patch/patch-angular-build.js, packages/angular-rspack-compiler/src/compilation/build-and-analyze.ts, packages/angular-rspack-compiler/src/compilation/index.ts, packages/angular-rspack-compiler/src/compilation/setup-compilation.ts, packages/angular-rspack-compiler/src/compilation/setup-compilation.unit.test.ts, packages/angular-rspack-compiler/src/compilation/setup-with-angular-compilation.ts, packages/angular-rspack-compiler/src/compilation/setup-with-angular-compilation.unit.test.ts, packages/angular-rspack-compiler/src/compilation/setup-with-paralell-compilation.ts, packages/angular-rspack-compiler/src/models/index.ts, packages/angular-rspack/src/lib/models/augmented-compilation.ts, packages/angular-rspack/src/lib/plugins/angular-rspack-plugin.ts, packages/angular-rspack/src/lib/plugins/loaders/angular-partial-transform.loader.ts
When `build --watch` or `serve` is run, the Compilation object (ParallelCompilation) is recreated every time.
During watch, the compilation object should be reused but updated with the latest modified files
=> feat(angular-rspack,angular-rspack-compiler): reuse existing compilation if exists

e2e/fixtures/rspack-csr-scss/rspack.config.js, packages/angular-rspack/package.json, packages/angular-rspack/src/lib/config/config-utils/common-config.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/models/unsupported-options.ts, packages/angular-rspack/src/lib/plugins/stats-json-plugin.ts, pnpm-lock.yaml
The `statsJson` option is currently unsupported and does nothing.
When `statsJson` is set to true, a `stat.json` file should be output
=> feat(angular-rspack): add statsJson plugin

packages/angular-rspack/src/lib/config/create-config.unit.test.ts, packages/angular-rspack/src/lib/models/unsupported-options.ts
Remove options that only exist in the Esbuild Application Builder
=> fix(angular-rspack): remove options that do not exist in Angular Webpack

e2e/fixtures/rspack-csr-css/rspack.config.js, packages/angular-rspack/src/lib/config/config-utils/common-config.ts, packages/angular-rspack/src/lib/config/create-config.unit.test.ts, packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/models/unsupported-options.ts, packages/angular-rspack/src/lib/utils/index-file/get-index-input-file.ts
=> feat(angular-rspack): add watch option

packages/angular-rspack-compiler/src/compilation/setup-compilation.ts, packages/angular-rspack/src/lib/plugins/angular-rspack-plugin.ts
If `componentStylesheetBundler.bundleFile()`/`componentStylesheetBundler.bundleInline()` doesn't throw an error but the results still contain errors, the errors will not be reported and the resulting style sheet will be empty.
This makes it really hard to understand, why certain styles are not compiled, as seen here: #76 
---
In addition, this fixes that both `sass` and `includePaths` are not passed to Angular's `ComponentStylesheetBundler`.
Fixes #76
=> fix(angular-rspack,angular-rspack-compiler): surface errors from ComponentStylesheetResult ensuring sass andincludePaths are passed

packages/angular-rspack/src/lib/models/angular-rspack-plugin-options.ts, packages/angular-rspack/src/lib/models/normalize-options.ts, packages/angular-rspack/src/lib/plugins/ng-rspack.ts
Closes https://github.com/nrwl/angular-rspack/issues/104
=> feat(angular-rspack): support index transformer

packages/angular-rspack/src/lib/plugins/ng-rspack.ts
Without this fix, `.gitkeep` files in nested folders will still make it into the copied assets.
=> fix(angular-rspack): fix ignore glob for .gitkeep

packages/angular-rspack/src/lib/config/config-utils/style-config-utils.ts
Support [sass pkg URL scheme](https://sass-lang.com/documentation/at-rules/use/#rules-for-a-pkg-importer)
Some UI Libraries export their Sass entry point via ⁠package.json. You can refer to the example below.
```
{
"exports": {
".": {
"sass": "styles/index.scss",
},
"./button.scss": {
"sass": "styles/button.scss",
},
"./accordion.scss": {
"sass": "styles/accordion.scss",
}
}
}
```
=> feat(angular-rspack): support pkg scheme importer
